apiVersion: v1
kind: Secret
metadata:
  name: aegis-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.database.password | quote }}
  DB_PASS: {{ .Values.database.password | quote }}
  Jwt__Secret: {{ .Values.jwt.secret | quote }}
  Auth__CommanderPassword: {{ .Values.auth.password | quote }}
